jobs:
  lint:
    commands:
      - flake8
      - pydocstyle
      - mypy .

  format:
    commands:
      - black .
      - isort --apply
      - autoflake . -ri --exclude "venv, conftest.py" --remove-all-unused-imports --remove-unused-variables

  pypi-upload:
    function: pypi_upload
    context:
      release_type: patch
      twine_username: joellefkowitz

routines:
  release:
    - comprehensiveTest
    - clean
    - format
    - updateDocs
    - pypi-upload

meta:
  script_root: ../
  project_root: ../../
